files <- Sys.glob(paste0("*", SHLIB_EXT))
xfiles <- Sys.glob("../inst/lib/*")
dest <- file.path(R_PACKAGE_DIR, paste0('libs', R_ARCH))
print(sprintf("selected dest = %s", dest))
dir.create(dest, recursive = TRUE, showWarnings = TRUE)
print(list.files(dest))
file.copy(files, dest, overwrite = TRUE)
file.copy(xfiles, dest, overwrite = TRUE)
if(file.exists("symbols.rds"))
    file.copy("symbols.rds", dest, overwrite = TRUE)

print("copied:")
for(s in c(files, xfiles)) print(sprintf("%s, ", s))
print(sprintf("to: %s\n", dest))

print("contents of dest:")
print(list.files(dest))

if (!file.exists(paste0(dest, "/", files)))
    warn(sprintf("file missing: %s", files))
