files <- Sys.glob(paste0("*", SHLIB_EXT))
xfiles <- Sys.glob(paste0("../inst/lib/*", SHLIB_EXT))
dest <- file.path(R_PACKAGE_DIR, paste0('libs', R_ARCH))
dir.create(dest, recursive = TRUE, showWarnings = FALSE)
file.copy(files, dest, overwrite = TRUE)
file.copy(xfiles, dest, overwrite = TRUE)
if(file.exists("symbols.rds"))
    file.copy("symbols.rds", dest, overwrite = TRUE)

print("copied:")
for(s in c(files, xfiles)) print(sprintf("%s, ", s))
print(sprintf("to: %s\n", dest))
