// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/SimpleSDESampler.h"
#include <Rcpp.h>

using namespace Rcpp;

// lpoly_make_system
XPtr<lpoly_system_type> lpoly_make_system(NumericMatrix cm, NumericMatrix trm);
RcppExport SEXP SimpleSDESampler_lpoly_make_system(SEXP cmSEXP, SEXP trmSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericMatrix >::type cm(cmSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type trm(trmSEXP );
        XPtr<lpoly_system_type> __result = lpoly_make_system(cm, trm);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// lpoly_model_matrix
NumericMatrix lpoly_model_matrix(XPtr<lpoly_system_type> lps, NumericMatrix data);
RcppExport SEXP SimpleSDESampler_lpoly_model_matrix(SEXP lpsSEXP, SEXP dataSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< XPtr<lpoly_system_type> >::type lps(lpsSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP );
        NumericMatrix __result = lpoly_model_matrix(lps, data);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// lpoly_implicit_sde
NumericMatrix lpoly_implicit_sde(XPtr<lpoly_system_type> sys, double sigma, NumericVector start, double from, double to, int steps);
RcppExport SEXP SimpleSDESampler_lpoly_implicit_sde(SEXP sysSEXP, SEXP sigmaSEXP, SEXP startSEXP, SEXP fromSEXP, SEXP toSEXP, SEXP stepsSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< XPtr<lpoly_system_type> >::type sys(sysSEXP );
        Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type start(startSEXP );
        Rcpp::traits::input_parameter< double >::type from(fromSEXP );
        Rcpp::traits::input_parameter< double >::type to(toSEXP );
        Rcpp::traits::input_parameter< int >::type steps(stepsSEXP );
        NumericMatrix __result = lpoly_implicit_sde(sys, sigma, start, from, to, steps);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// lpoly_implicit_sde_averages
NumericMatrix lpoly_implicit_sde_averages(int nrep, XPtr<lpoly_system_type> sys, double sigma, NumericVector start, double from, double to, int steps);
RcppExport SEXP SimpleSDESampler_lpoly_implicit_sde_averages(SEXP nrepSEXP, SEXP sysSEXP, SEXP sigmaSEXP, SEXP startSEXP, SEXP fromSEXP, SEXP toSEXP, SEXP stepsSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< int >::type nrep(nrepSEXP );
        Rcpp::traits::input_parameter< XPtr<lpoly_system_type> >::type sys(sysSEXP );
        Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type start(startSEXP );
        Rcpp::traits::input_parameter< double >::type from(fromSEXP );
        Rcpp::traits::input_parameter< double >::type to(toSEXP );
        Rcpp::traits::input_parameter< int >::type steps(stepsSEXP );
        NumericMatrix __result = lpoly_implicit_sde_averages(nrep, sys, sigma, start, from, to, steps);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// solve_general_sde
NumericMatrix solve_general_sde(Rcpp::Function d_det, Rcpp::Function d_stoch, vector<double> start, double from, double to, int steps);
RcppExport SEXP SimpleSDESampler_solve_general_sde(SEXP d_detSEXP, SEXP d_stochSEXP, SEXP startSEXP, SEXP fromSEXP, SEXP toSEXP, SEXP stepsSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< Rcpp::Function >::type d_det(d_detSEXP );
        Rcpp::traits::input_parameter< Rcpp::Function >::type d_stoch(d_stochSEXP );
        Rcpp::traits::input_parameter< vector<double> >::type start(startSEXP );
        Rcpp::traits::input_parameter< double >::type from(fromSEXP );
        Rcpp::traits::input_parameter< double >::type to(toSEXP );
        Rcpp::traits::input_parameter< int >::type steps(stepsSEXP );
        NumericMatrix __result = solve_general_sde(d_det, d_stoch, start, from, to, steps);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// solve_implicit_sde
NumericMatrix solve_implicit_sde(Rcpp::Function d_det, Rcpp::Function d_stoch, Rcpp::Function jacobian, double sigma, NumericVector start, double from, double to, int steps);
RcppExport SEXP SimpleSDESampler_solve_implicit_sde(SEXP d_detSEXP, SEXP d_stochSEXP, SEXP jacobianSEXP, SEXP sigmaSEXP, SEXP startSEXP, SEXP fromSEXP, SEXP toSEXP, SEXP stepsSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< Rcpp::Function >::type d_det(d_detSEXP );
        Rcpp::traits::input_parameter< Rcpp::Function >::type d_stoch(d_stochSEXP );
        Rcpp::traits::input_parameter< Rcpp::Function >::type jacobian(jacobianSEXP );
        Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type start(startSEXP );
        Rcpp::traits::input_parameter< double >::type from(fromSEXP );
        Rcpp::traits::input_parameter< double >::type to(toSEXP );
        Rcpp::traits::input_parameter< int >::type steps(stepsSEXP );
        NumericMatrix __result = solve_implicit_sde(d_det, d_stoch, jacobian, sigma, start, from, to, steps);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// solve_implicit_sde_averages
NumericMatrix solve_implicit_sde_averages(int nrep, Rcpp::Function d_det, Rcpp::Function d_stoch, Rcpp::Function jacobian, double sigma, NumericVector start, double from, double to, int steps);
RcppExport SEXP SimpleSDESampler_solve_implicit_sde_averages(SEXP nrepSEXP, SEXP d_detSEXP, SEXP d_stochSEXP, SEXP jacobianSEXP, SEXP sigmaSEXP, SEXP startSEXP, SEXP fromSEXP, SEXP toSEXP, SEXP stepsSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< int >::type nrep(nrepSEXP );
        Rcpp::traits::input_parameter< Rcpp::Function >::type d_det(d_detSEXP );
        Rcpp::traits::input_parameter< Rcpp::Function >::type d_stoch(d_stochSEXP );
        Rcpp::traits::input_parameter< Rcpp::Function >::type jacobian(jacobianSEXP );
        Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type start(startSEXP );
        Rcpp::traits::input_parameter< double >::type from(fromSEXP );
        Rcpp::traits::input_parameter< double >::type to(toSEXP );
        Rcpp::traits::input_parameter< int >::type steps(stepsSEXP );
        NumericMatrix __result = solve_implicit_sde_averages(nrep, d_det, d_stoch, jacobian, sigma, start, from, to, steps);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
