# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' LPoly system constructor
#' Returns and XPtr to an lpoly_system_type object
#' @param cm Model coefficient matrix
#' @param trm Model term specification, as generated by lpoly_model_spec (each row represents the powers of the different factors in a term)
#' @export
lpoly_make_system <- function(cm, trm) {
    .Call('SimpleSDESampler_lpoly_make_system', PACKAGE = 'SimpleSDESampler', cm, trm)
}

#' LPoly model matrix generator
#' Builds the model matrix from the data using the lpoly_system_type object
#' @param lps XPtr to an lpoly_system_type object created by a call to lpoly_make_system
#' @param data One column per measurement variable
#' @export
lpoly_model_matrix <- function(lps, data) {
    .Call('SimpleSDESampler_lpoly_model_matrix', PACKAGE = 'SimpleSDESampler', lps, data)
}

#' LPoly System Implicit SDE Simulator
#' Simulates a trajectory to the SDE specified by *sys* and the noise level sigma, starting at the point start and integrating over times [*from*,*to*] on *steps + 1* time points.
#' @param sys lpoly_system_type XPtr object created with lpoly_make_system
#' @param sigma Amplitude of noise: scalar
#' @param start Initial position: n vector
#' @param from Initial time: scalar
#' @param to Final time: scalar
#' @param steps Number of points to take, s.t. dt = (from - to) / (steps + 1): integer
#' @export
lpoly_implicit_sde <- function(sys, sigma, start, from, to, steps) {
    .Call('SimpleSDESampler_lpoly_implicit_sde', PACKAGE = 'SimpleSDESampler', sys, sigma, start, from, to, steps)
}

#' LPoly System Implicit SDE Simulator: time-wise averages
#' Samples multiple times from lpoly_implicit_sde and returns the time-wise average
#' @param nrep Number of repetitions to average over: integer
#' @param sys lpoly_system_type XPtr object created with lpoly_make_system
#' @param sigma Amplitude of noise: scalar
#' @param start Initial position: n vector
#' @param from Initial time: scalar
#' @param to Final time: scalar
#' @param steps Number of points to take, s.t. dt = (from - to) / (steps + 1): integer
#' @export
lpoly_implicit_sde_averages <- function(nrep, sys, sigma, start, from, to, steps) {
    .Call('SimpleSDESampler_lpoly_implicit_sde_averages', PACKAGE = 'SimpleSDESampler', nrep, sys, sigma, start, from, to, steps)
}

#' @export
solve_general_sde <- function(d_det, d_stoch, start, from, to, steps) {
    .Call('SimpleSDESampler_solve_general_sde', PACKAGE = 'SimpleSDESampler', d_det, d_stoch, start, from, to, steps)
}

#' General implicit SDE simulator
#' @param d_det Deterministic component: an R function: (m x n matrix of m states, scalar time) -> m x n matrix of m time derivatives
#' @param d_stoch Stochastic component: an R function: (1 x n matrix state, scalar time) -> 1 x n matrix state
#' @param jacobian Jacobian of deterministic component: an R function: (1 x n matrix state, scalar time) -> n x n matrix df_i / du_j
#' @param sigma Amplitude of noise: scalar
#' @param start Initial position: n vector
#' @param from Initial time: scalar
#' @param to Final time: scalar
#' @param steps Number of points to take, s.t. dt = (from - to) / (steps + 1): integer
#' @export
solve_implicit_sde <- function(d_det, d_stoch, jacobian, sigma, start, from, to, steps) {
    .Call('SimpleSDESampler_solve_implicit_sde', PACKAGE = 'SimpleSDESampler', d_det, d_stoch, jacobian, sigma, start, from, to, steps)
}

#' General implicit SDE simulator: time-wise averages
#' @param nrep Number of repetitions to average over: integer
#' @param d_det Deterministic component: an R function: m x n matrix of m states -> m x n matrix of m time derivatives
#' @param d_stoch Stochastic component: an R function: (1 x n matrix state, scalar time) -> 1 x n matrix state
#' @param jacobian Jacobian of deterministic component: an R function: (n vector state, scalar time) -> n x n matrix df_i / du_j
#' @param sigma Amplitude of noise: scalar
#' @param start Initial position: n vector
#' @param from Initial time: scalar
#' @param to Final time: scalar
#' @param steps Number of points to take, s.t. dt = (from - to) / (steps + 1): integer
#' @export
solve_implicit_sde_averages <- function(nrep, d_det, d_stoch, jacobian, sigma, start, from, to, steps) {
    .Call('SimpleSDESampler_solve_implicit_sde_averages', PACKAGE = 'SimpleSDESampler', nrep, d_det, d_stoch, jacobian, sigma, start, from, to, steps)
}

