# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
solve_general_sde <- function(d_det, d_stoch, start, from, to, steps) {
    .Call('SimpleSDESampler_solve_general_sde', PACKAGE = 'SimpleSDESampler', d_det, d_stoch, start, from, to, steps)
}

#' @export
solve_implicit_sde <- function(d_det, d_stoch, jacobian, start, from, to, steps) {
    .Call('SimpleSDESampler_solve_implicit_sde', PACKAGE = 'SimpleSDESampler', d_det, d_stoch, jacobian, start, from, to, steps)
}

